### ISSUE TITLE
Create: Root number per plant

### ISSUE THREAD

**Issue by celineaubert** [Planteome/CO_334-cassava-traits#128]
Currently there are 2 similar traits in the ontology: 
- CO_334:0000405 : Marketable root number
- CO_334:0000452: Root number (definition: Number of harvested marketable storage roots)
One of those traits could be delete from the ontology as they both represent the same thing, or it they do not represent the same thing, the definitions could be updated to better understand the difference. 

The number of roots per plant is missing as a morphological trait.

**Comment by celineaubert** [comment]
Updating the issue: first part has been reported in issue #138 .
The sedonc part is still need: 
Term: '' Root number per plant'' 
Definition: The number of storage roots per plant.

**Comment by nmenda** [comment]
resolved here https://github.com/Planteome/CO_334-cassava-traits/issues/138
