### ISSUE TITLE
Create: cassava blight leaf spot disease severity

### ISSUE THREAD

**Issue by LucianoRogerio** [Planteome/CO_334-cassava-traits#134]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Luciano Rogerio Braatz de Andrade    |
| **Program** | Cornell University |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | cassava blight leaf spot disease severity    |
| **Proposed Synonyms**  | Severidade a doenca da Queima das Folhas da mandioca     |
| **Definition**         | Visual rating of symptoms in response to the blight leaf spot disease caused by Passalora vicosae. Symptoms rated from: 0 = clean, no infection, 1 = Few leaves affected from the lower third part of the plant, 2 = Low incidence at the lower third part of the plant, 3 = middle incidence distributed at the lower and middle parts of the plant with yellowed leaves and/or defoliation, 4 = high incidence distributed all over the plant with yellowed leaves and/or defoliation, 5 = Plant fully defoliated.     |
| **Trait Class**        | Biotic Stress   |
| **Measurement Method** | Visual rating of symptoms in response to the blight leaf spot disease        |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description                   |
| -------- | ----------------------------- |
| **0** | clean, no infection    |
| **1** | Few leaves affected from the lower third part of the plant    |
| **2** | Low incidence at the lower third part of the plant    |
| **3** | middle incidence distributed at the lower and middle parts of the plant with yellowed leaves and/or defoliation    |
| **4** | high incidence distributed all over the plant with yellowed leaves and/or defoliation    |
| **5** | Plant fully defoliated    |

**Comment by nmenda** [comment]
terms added here https://github.com/Planteome/CO_334-cassava-traits/pull/137/files
