### ISSUE TITLE
Update definition for root number

### ISSUE THREAD

**Issue by celineaubert** [Planteome/CO_334-cassava-traits#138]
the current definition of Root number ([CO_334:0000452](https://cropontology.org/rdf/CO_334:0000452)) correspond to another term in the ontology: Marketable roots number. 

Please update the definition to : "Number of storage roots'', and modify the synonyms accordingly, so this trait can be used properly to annotate the number of all storage roots (marketable and non- marketable).

**Comment by nmenda** [comment]
term updated in cassavabase
