### ISSUE TITLE
Create: Solubility

### ISSUE THREAD

**Issue by UEkanem** [Planteome/CO_334-cassava-traits#192]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Ukoabasi Ekanem    |
| **Program** | International Institute of Tropical Agriculture (IITA), Ibadan |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Solubility    |
| **Proposed Synonyms**  | Sol KSP =(A+)a(B-)b     |
| **Definition**         | Solubility of gari is expressed in units of mass divided by volume, such as grams per liter and is the property of gari to dissolve in distilled water  at 55 degree for 30 minutes     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Measured by dissolving the gari sample in distilled water and mixed using a Wortex-mixer.        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | %          |

**Comment by UEkanem** [comment]
#192

**Comment by nmenda** [comment]
closed with #195

**Comment by UEkanem** [comment]
Closed with #192
