### ISSUE TITLE
Create: Relative Growth Rate (volume)

### ISSUE THREAD

**Issue by JuanQuirosCR** [Planteome/CO_334-cassava-traits#229]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Juan Jose Quiros Vargas    |
| **Program** | Julich Forschungszentrum |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Relative Growth Rate (volume)    |
| **Proposed Synonyms**  | RGR_vol     |
| **Definition**         | It refers to the speed of the crop growth in terms of volume per unit of time (generally used per day).

Note: the trait type should be &#34;remote sensing&#34;, yet, since this option was not in the list above, then I choose &#34;agronomic&#34;.     |
| **Trait Class**        | Agronomic   |
| **Measurement Method** | Remote sensing, from unmanned aerial vehicles (UAV).        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | m3/day          |

**Comment by nmenda** [comment]
added and merged https://github.com/Planteome/CO_334-cassava-traits/pull/234
