### ISSUE TITLE
Question about cassava disc color trait (CO_334:0000360)

### ISSUE THREAD

**Issue by cooperl09** [Planteome/CO_334-cassava-traits#25]
Is this the color of the flowers or a disc of the tuber?  I am not sure where to map it to without knowing that.  The term TO:1000019 ! disk flower color refers to disk flowers in a capitulum type inflorescence, such as those in the Asteraceae, which is different than those in Cassava.  
http://dev.planteome.org/amigo/term/PO:0025332

[Term]
id: CO_334:0000360
name: cassava disc color trait
def: "Color of disc" [CO:curators]
synonym: "discol" EXACT []
is_a: TO:1000019 ! disk flower color

**Comment by dws409** [comment]
Yes, you are correct.  Disk flowers are a feature of the Sunflower family and Cassava does not have them and is not in that Sunflower family.  I would assume that this refers to the tuber having seen many cultivars myself in Brazil There are some the are bright yellow, light yellow, and white.

Dennis

**Comment by cooperl09** [comment]
The method description states: "Visual rating of floral disc color" 
and the scales are:  1 = White | 2 = Orange | 3 = Green | 4 = Red | 5 = Purple

So perhaps this should just be flower color (TO:0000537)?

**Comment by dws409** [comment]
Cassava has white, pink, red, and purplish flowers in a raceme.  Orange and green seem odd to me.  Green might be before and during opening.

**Comment by cooperl09** [comment]
@aafolabi Could you please clarify this for us?  Is this referring to the tuber color or the flower color?

**Comment by aafolabi** [comment]
Hi Laurel, it is the floral disc color. The floral disc in cassava seats the flower ovary and style inside the perianth. Most of these color variations do exist but found less often. Green (during development), yellow (often in male flower) and white are very common.

**Comment by cooperl09** [comment]
Thanks Afola, that helps- I found an on the web- http://www.uq.edu.au/_School_Science_Lessons/64.6.0.GIF
Is this structure what you are referring to?

**Comment by cooperl09** [comment]
I believe it is part of the receptacle? @dws409  what do you think?
