### ISSUE TITLE
plot volume

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/CO_334-cassava-traits#48]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | anna van doorn    |
| **Program** | Juelich |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | plot volume    |
| **Definition**         | From Drone image analysis
The parameters from the distribution fit are unit less: shape and scale parameters are define has in: https://en.wikipedia.org/wiki/Weibull_distribution     |
| **Trait Class**        | Agronomic   |
| **Measurement Method** | The volume is the sum of all z-values (the height of every point in the point cloud), times 0.01x0.01 (every pixel is 1 cm res)         |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | m3           |

**Comment by nmenda** [comment]
CO_334:0002032
