### ISSUE TITLE
Plant/plot height (m)

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/CO_334-cassava-traits#49]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | anna van doorn    |
| **Program** | juelich |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Plant/plot height (m)    |
| **Definition**         | From drone image analysis:
The height is calculated from the mean of the 5% highest points in a plot point cloud (top 95 percentile)

     |
| **Trait Class**        | Agronomic   |
| **Measurement Method** | The height is calculated from the mean of the 5% highest points in a plot point cloud (top 95 percentile)        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | meter           |

**Comment by nmenda** [comment]
CO_334:0002033
