### ISSUE TITLE
inconsistencies between obo file and TD - CO_334:0000077

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/CO_334-cassava-traits#56]
The scale information is missing in the obo file for this variable yet it is described in the TD as:

CO_334:0100678 | 11pt scale | Ordinal |   |   |   |   | 0 = No symptom of root discoloration | 3 = 30% of the root surface has root discoloration | 4 = 40% of the root surface has root discoloration | 1=10% of the root surface has root discoloration | 2 = 20% of the root surface has root discoloration | 7 = 70% of the root surface has root discoloration | 8 = 80% of the root surface has root discoloration | 5 = 50% of the root surface has root discoloration | 6 = 60% of the root surface has root discoloration | 10 = 100% of the root surface has root discoloration
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Since the ID CO_334:0100678 is used in the obo file, I would recommend to add back this scale with a different ID.

Variable info in the obo file:
```
[Term]
id: CO_334:0000077
name: cassava post-harvest physiological deterioration variable 0-10 variable
def: "Internal root discoloration or vascular streaking that renders cassava roots unfit for human or animal consumption.\nA number of root samples are cut into 7 slices  and each slice is scored on a 0-10 scale." [CO:curators]
relationship: variable_of CO_334:0000266 ! post-harvest physiological deterioration
relationship: variable_of CO_334:0010001 ! Estimation: post-harvest physiological deterioration method
```

**Comment by nmenda** [comment]
resolved in cassavabase
