### ISSUE TITLE
Number of inflorescence by branch level

### ISSUE THREAD

**Issue by marieALaporte** [Planteome/CO_334-cassava-traits#65]
Number of inflorescence by branch level should not be a subclass of days to first inflorescence. It should go under CO_334:0000336 ! Flower and flowering morphological trait

```
[Term]
id: CO_334:0000525
name: Number of inflorescence by branch level
namespace: cassava_trait
def: "Number of inflorescence at specific branching level." [CO:curator]
is_a: CO_334:0000359 ! Days to first inflorescence
created_by: AAfolabi
creation_date: 2017-07-25T15:54:07Z
```

**Comment by nmenda** [comment]
https://github.com/Planteome/CO_334-cassava-traits/blob/master/cassava_trait.obo#L5632
