### ISSUE TITLE
Create: Canopy width measured in centimeters

### ISSUE THREAD

**Issue by LucianoRogerio** [Planteome/CO_334-cassava-traits#68]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | LUCIANO ROGERIO BRAATZ DE ANDRADE    |
| **Program** | EMBRAPA |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Canopy width measured in centimeters    |
| **Definition**         | length measurement with metric ruler in centimeter     |
| **Trait Class**        | Morphological   |
| **Measurement Method** | width measurement with metric ruler in centimeters        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | cm          |

**Comment by nmenda** [comment]
CO_334:0002038
