### ISSUE TITLE
Create: Pasting temperature

### ISSUE THREAD

**Issue by kanaabim** [Planteome/CO_334-cassava-traits#90]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Michael Kanaabi    |
| **Program** | NaCRRI |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Pasting temperature    |
| **Definition**         | Temperature at which the viscosity trace first raises above the baseline during the initial heating phase.     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Measured by the Rapid Visco Analyser (RVA)        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | Degrees Celsius          |

**Comment by kanaabim** [comment]
Pasting temperature as measured by the RVA is used to infer on the quality of flours.

**Comment by nmenda** [comment]
CO_334:0002100
