### ISSUE TITLE
Create: Peak 

### ISSUE THREAD

**Issue by kanaabim** [Planteome/CO_334-cassava-traits#91]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Michael Kanaabi    |
| **Program** | NaCRRI |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Peak    |
| **Proposed Synonyms**  | Peak viscosity, Maximum hot paste viscosity     |
| **Definition**         | Maximum viscosity during the heating or hold phase of the RVA test     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Measured by the Rapid Visco Analyser (RVA)        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | Degrees Celsius          |

**Comment by nmenda** [comment]
CO_334:0002107
