### ISSUE TITLE
Create: Breakdown

### ISSUE THREAD

**Issue by kanaabim** [Planteome/CO_334-cassava-traits#93]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Michael Kanaabi    |
| **Program** | NaCRRI |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Breakdown    |
| **Definition**         | Breakdown equals peak viscosity minus trough viscosity     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Measured with the Rapid Visco Analyzer (RVA)        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | Pascal-second (Pa-s)          |

**Comment by nmenda** [comment]
CO_334:0002105
