### ISSUE TITLE
Create: Setback

### ISSUE THREAD

**Issue by kanaabim** [Planteome/CO_334-cassava-traits#95]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Michael Kanaabi    |
| **Program** | NaCRRI |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Setback    |
| **Definition**         | Final viscosity minus trough viscosity     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Measured on cassava flour using the Rapid Visco Analyzer (RVA)        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | Pa-s          |

**Comment by nmenda** [comment]
CO_334:0002103
