### ISSUE TITLE
Create: Moisture content of cassava flour in percentage

### ISSUE THREAD

**Issue by kanaabim** [Planteome/CO_334-cassava-traits#96]
## Submitter

|             |                            |
| ----------- | -------------------------- |
| **Name**    | Michael Kanaabi    |
| **Program** | NaCRRI |

## Creation Request

|                        |                                  |
| ---------------------- | -------------------------------- |
| **Trait Name**         | Moisture content of cassava flour in percentage    |
| **Definition**         | Amount of moisture retained in cassava flour after milling     |
| **Trait Class**        | Quality   |
| **Measurement Method** | Determined as the loss in weight of a flour sample after oven drying expressed as a proportion of the original weight prior to oven drying        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | Percentage (%)          |

**Comment by elizabetharnaud** [comment]
@kanaabim @aafolabi 
We usually do not integrate the unit  (in this case %)in the trait name  otherwise we will multiply in the ontology the same trait just to integrate the measurement unit of scale that may change over time or in various project. I suggest to only keep 'Moisture content of cassava flour' and the % will indicate at the measurement method level.

**Comment by kanaabim** [comment]
> @kanaabim @aafolabi
> We usually do not integrate the unit (in this case %)in the trait name otherwise we will multiply in the ontology the same trait just to integrate the measurement unit of scale that may change over time or in various project. I suggest to only keep 'Moisture content of cassava flour' and the % will indicate at the measurement method level.
Thank you @elizabetharnaud . This is well noted

**Comment by nmenda** [comment]
CO_334:0002102
